name: Generate ASCII Artwork

on: push

jobs: 
    build_job:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Install cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay CMD
        run: cowsay -f dragon "Run for cover, dragon. Fire......." >> dragon.txt

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v3
        with:
            name: deagon-text-file
            path: dragon.txt
            
    test_job:
      needs: build_job
      runs-on: ubuntu-latest
      steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v3
        with:
            name: deagon-text-file
            path: dragon.txt

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt

    deploy_job:
      needs: test_job
      runs-on: ubuntu-latest
      steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v3
        with:
            name: deagon-text-file
            path: dragon.txt

      - name: Read File
        run: cat dragon.txt
      
      - name: Deploy
        run: echo Deploying.....