name: Matrix Workflow Example

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - os: windows-latest
            images: alpine
        include:
          - os: ubuntu-20.04
            images: amd64/alpine
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker version
        run: docker version

      - name: Docker info
        run: docker info

      - name: Pull Docker image ${{ matrix.images }}
        run: docker pull ${{ matrix.images }}

      - name: Run Docker image on Linux with timeout
        if: runner.os != 'Windows'
        run: timeout 60s docker run ${{ matrix.images }} || echo "docker run timed out"
        shell: bash

      - name: Run Docker image on Windows without timeout
        if: runner.os == 'Windows'
        run: docker run ${{ matrix.images }}
        shell: powershell
