name: Matrix Workflow Example

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - os: windows-latest
            images: alpine
        include:
          - os: ubuntu-20.04
            images: amd64/alpine
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Docker info
        run: docker info

      - name: Run Docker image ${{ matrix.images }} on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}
